config/routes.rb
Rails.application.routes.draw do
  get 'store/index'
  devise_for :users
  root to: "pages#home"

  get "up" => "rails/health#show", as: :rails_health_check

  resources :products do
    resources :bookings, only: [:create]

    collection do
      get :search
    end

    member do
      patch 'update_active'
      patch 'add_photos'
      delete 'destroy_photo'
    end

  end

  resources :bookings, only: [:show, :index, :destroy, :update]
  resources :profiles, only: [:show, :update]
  resources :stores, only: [:index]
  get 'stores/ads', to: 'products#summary', as: 'product_summary'
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :authenticate_user!, only: [:index]
  def index
    @user = current_user
    @products = Product.where(user_id: @user)
    @bookings = Booking.joins(:product).where(products: { user_id: @user })
  end


  private

  def booking_params
    params.require(:booking).permit(:status)
  end
end

app/views/stores/_bookings_table.html.erb
<div class="table-responsive">
  <table class="table table-hover align-middle">
    <thead class="table-light">
      <tr>
        <th>Locataire</th>
        <th>Produit</th>
        <th>Départ</th>
        <th>Retour</th>
        <th>Montant</th>
        <th>Status</th>
      </tr>
    </thead>
    <tbody>
      <% bookings.each do |item| %>
        <tr>
          <td>
            <%= link_to booking_path(item) do %>
              <div class="d-flex align-items-center">
              <% if item.user.photo.present? %>
                  <%= cl_image_tag item.user.photo.key, class: "avatar",  style: "max-width: 50px;" %>
                <% else %>
                  <%= image_tag 'no_profile.png', class: "avatar", alt: "No picture available", height: 50, width: 50 %>
                <% end %>
                <span class="mx-3"><%= item.user.username %></span>

              </div>
            <% end %>
          </td>
          <% if item.product.photos.present? %>
            <td><%= cl_image_tag item.product.photos[0].key , class: "rounded", height: 50, width: 50 %></td>
          <% else %>
            <td><%= image_tag 'no_picture.jpg', class: "rounded", alt: "No picture available", height: 50, width: 50 %></td>
          <% end %>
          <td><%= link_to item.start_date, booking_path(item) %></td>
          <td><%= link_to item.end_date, booking_path(item) %></td>
          <td><%= link_to "#{item.amount} €", booking_path(item) %></td>
          <td class="text-end">
            <select class="form-select form-select-sm custom-select"
                    data-controller="status"
                    data-action="change->status#updateStatus"
                    data-booking-id="<%= item.id %>">
              <option value="Pending" <%= "selected" if item.status == "Pending" %>>En attente</option>
              <option value="Accepted" <%= "selected" if item.status == "Accepted" %>>Acceptée</option>
              <option value="Refused" <%= "selected" if item.status == "Refused" %>>Annulée</option>
            </select>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/stores/index.html.erb
<div class="dashboard-renter container py-5">

  <div class="dashboard-header d-flex justify-content-between align-items-center mb-5">
    <div>
      <h1 class="dashboard-title fw-bold">Bonjour <%= @user.first_name %> <span>👋</span></h1>
      <p class="dashboard-subtitle text-secondary fs-5">Bienvenue dans votre espace loueur</p>
    </div>
  </div>


  <div class="dashboard-stats row mb-5 g-4">
    <div class="col-md-4">
      <div class="dashboard-card card shadow-sm border-0 text-center p-4">
        <div class="card-body">
          <h4 class="dashboard-card-title text-muted mb-3 text-align-left">Revenu total </h4>
          <p class="dashboard-card-value display-4 fw-bold "><%= @bookings.where(status: 'Accepted').sum(:amount) %> €</p>
        </div>
      </div>
    </div>
    <div class="col-md-4">
      <div class="dashboard-card card shadow-sm border-0 text-center p-4">
        <div class="card-body">
          <h4 class="dashboard-card-title text-muted mb-3">Locations validé</h4>
          <p class="dashboard-card-value display-4 fw-bold "><%= @bookings.where(status: 'Accepted').count %></p>
        </div>
      </div>
    </div>
    <div class="col-md-4">
      <div class="dashboard-card card shadow-sm border-0 text-center p-4">
        <div class="card-body">
          <h4 class="dashboard-card-title text-muted mb-3">Locations en attente</h4>
          <p class="dashboard-card-value display-4 fw-bold "><%= @bookings.where(status: 'Pending').count %></p>
        </div>
      </div>
    </div>
  </div>


  <div class="dashboard-shop mb-5">
    <h3 class="dashboard-section-title fw-bold mb-3">Votre boutique</h3>
    <p class="dashboard-section-subtitle text-muted mb-4">Développer votre activité sur KilouTools</p>
    <div class="row g-4">
      <div class="col-md-6">
        <div class="dashboard-card card shadow-sm border-0 text-center p-4">
          <%=link_to new_product_path do %>
              <div class="card-body">
                <div class = "d-flex ">
                  <%= image_tag 'add.png', height: 20, width: 20 %>
                  <h5 class="dashboard-card-title text-dark fw-bold mb-2 mx-2">Ajouter un produit</h5>
                </div>
                <p class="dashboard-card-text text-muted">Augmentez votre parc matériel en ajoutant des produits</p>
            </div>
          <% end %>
        </div>
      </div>
      <div class="col-md-6">
        <div class="dashboard-card card shadow-sm border-0 text-center p-4">
          <%=link_to product_summary_path do %>
              <div class="card-body">
                <div class="d-flex ">
                  <%= image_tag 'list.png', height: 20, width: 20 %>
                  <h5 class="dashboard-card-title text-dark fw-bold mb-2 mx-2">Mes annonces</h5>
              </div>
              <p class="dashboard-card-text text-muted">Modifiez vos produits en location</p>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>

  <div class="dashboard-reservations">
    <h3 class="dashboard-section-title fw-bold mb-3">Vos réservations</h3>
    <p class="dashboard-section-subtitle text-muted mb-4">Les réservations que vous avez reçues</p>
    <% if @bookings.any? %>
        <ul class="nav nav-tabs mb-4 filtered-tabs" id="reservationTabs" role="tablist">
          <li class="nav-item" role="presentation">
              <button class="nav-link active" id="all-tab" data-bs-toggle="tab" data-bs-target="#all" type="button" role="tab">
                  Toutes <span class="notif"><%= @bookings.count if @bookings.count > 0 %></span>
              </button>
          </li>
          <li class="nav-item" role="presentation">
              <button class="nav-link" id="cancelled-tab" data-bs-toggle="tab" data-bs-target="#cancelled" type="button" role="tab">
                  Annulées
                  <% if @bookings.select { |booking| booking.status == 'Refused' }.count > 0 %>
                    <span class="notif"><%= @bookings.select { |booking| booking.status == 'Refused' }.count %></span>
                  <% end %>
              </button>
          </li>
          <li class="nav-item" role="presentation">
              <button class="nav-link" id="accepted-tab" data-bs-toggle="tab" data-bs-target="#accepted" type="button" role="tab">
                  Acceptées
                  <% if @bookings.select { |booking| booking.status == 'Accepted' }.count > 0 %>
                    <span class="notif"><%= @bookings.select { |booking| booking.status == 'Accepted' }.count %></span>
                  <% end %>
              </button>
          </li>
          <li class="nav-item" role="presentation">
              <button class="nav-link" id="pending-tab" data-bs-toggle="tab" data-bs-target="#pending" type="button" role="tab">
                  En attente
                  <% if @bookings.select { |booking| booking.status == 'Pending' }.count > 0 %>
                    <span class="notif"><%= @bookings.select { |booking| booking.status == 'Pending' }.count %></span>
                  <% end %>
              </button>
          </li>
      </ul>

        <div class="tab-content" id="reservationTabsContent">
          <div class="tab-pane fade show active" id="all" role="tabpanel">
            <%= render 'bookings_table', bookings: @bookings %>
          </div>
          <div class="tab-pane fade" id="accepted" role="tabpanel">
            <%= render 'bookings_table', bookings: @bookings.select { |b| b.status == 'Accepted' } %>
          </div>
          <div class="tab-pane fade" id="cancelled" role="tabpanel">
            <%= render 'bookings_table', bookings: @bookings.select { |b| b.status == 'Refused' } %>
          </div>
          <div class="tab-pane fade" id="pending" role="tabpanel">
            <%= render 'bookings_table', bookings: @bookings.select { |b| b.status == 'Pending' } %>
          </div>
        </div>
    <% else %>
      <p>Aucune réservation pour le moment.</p>
  <% end %>
</div>