config/routes.rb
Rails.application.routes.draw do
  get 'store/index'
  devise_for :users
  root to: "pages#home"

  get "up" => "rails/health#show", as: :rails_health_check

  resources :products do
    resources :bookings, only: [:create]

    collection do
      get :search
    end

    member do
      patch 'update_active'
      patch 'add_photos'
      delete 'destroy_photo'
    end

  end

  resources :bookings, only: [:show, :index, :destroy, :update]
  resources :profiles, only: [:show, :update]
  resources :stores, only: [:index]
  get 'stores/ads', to: 'products#summary', as: 'product_summary'
end

app/views/shared/_add_booking_form.html.erb
<%= simple_form_for(booking, url: product_bookings_path(params[:id]), html: { class: "form-container p-4 bg-white rounded" }) do |f| %>
  <div class="form-group d-none">
    <%= f.input :product_id, as: :hidden, input_html: { value: params[:product_id] } %>
  </div>
  <h2 class="mb-4">Choisissez votre plage de dates</h2>


  <div data-controller="datepicker">
    <div class="mb-4">
    <p class="fs-4 fw-bold">
      <span data-datepicker-target="price" class="color-orange"> <%= price %>€</span>
    </p>
    <p>
      <span data-datepicker-target="slot">TTC / jour</span>
    </p>
    </div>

    <div  class="mb-4">
      <div class="mb-3">
        <%= f.hidden_field :bookings_dates, value: bookings_dates, data: { datepicker_target: "bookingsDates" } %>
        <%= f.label :start_date, "Date de début location", class: "form-label fw-bold" %>
        <%= f.text_field :start_date, as: :string, class: "form-control", value: start_date, placeholder: "Choisissez une date", data: { datepicker_target: "startDate" } %>
      </div>

      <div class="mb-3">
        <%= f.label :end_date, "Date de fin location", class: "form-label fw-bold" %>
        <%= f.text_field :end_date, as: :string, class: "form-control", value: end_date, placeholder: "Choisissez une date", data: { datepicker_target: "endDate" } %>
      </div>

      <div class="mb-4">
        <%= f.hidden_field :price_per_day, value: price, data: { datepicker_target: "pricePerDay" } %>
        <%= f.hidden_field :amount, value: price, data: { datepicker_target: "amount" } %>
      </div>
    </div>

    <div class="form-actions">
      <%= f.submit "Réserver", class: "btn btn-primary btn-lg w-100" %>
    </div>
  </div>
<% end %>

app/views/shared/_card.html.erb
<div class="card">
  <div class="card-header">
    <div class="availability">
      <span class="status-circle"></span>
      <span>Disponibilité confirmée</span>
    </div>
    <img
      src="profile.jpg"
      alt="Profile photo"
      class="profile-img"
    />
  </div>
  <div class="card-body">
    <h3>Marouane</h3>
    <p class="location">
      <span>📍</span> Localisé(e) à Paris 15e Arrondissement
    </p>
    <p class="rate">400 €/jour</p>
    <p class="description">
      Développeur Fullstack JS: Next JS/React JS/Node JS
    </p>
    <div class="rating">
      ⭐⭐⭐⭐⭐ <span>(2)</span>
    </div>
    <div class="tags">
      <span class="tag">Next.js</span>
      <span class="tag">React.js</span>
      <span class="tag">JavaScript</span>
      <span class="tag">Stratégie SEO</span>
      <span class="tag">Développement web</span>
      <span class="tag">Node.js</span>
    </div>
  </div>
</div>

app/views/shared/_filtered_bookings_list.html.erb
<ul class="nav nav-tabs mb-4 filtered-tabs" id="reservationTabs" role="tablist">
    <li class="nav-item" role="presentation">
        <button class="nav-link active" id="all-tab" data-bs-toggle="tab" data-bs-target="#all" type="button" role="tab">
            Toutes <span class="notif"><%= @bookings.count if @bookings.count > 0 %></span>
        </button>
    </li>
    <li class="nav-item" role="presentation">
        <button class="nav-link" id="cancelled-tab" data-bs-toggle="tab" data-bs-target="#cancelled" type="button" role="tab">
            Annulées
            <% if @bookings.select { |booking| booking.status == 'Refused' }.count > 0 %>
              <span class="notif"><%= @bookings.select { |booking| booking.status == 'Refused' }.count %></span>
            <% end %>
        </button>
    </li>
    <li class="nav-item" role="presentation">
        <button class="nav-link" id="accepted-tab" data-bs-toggle="tab" data-bs-target="#accepted" type="button" role="tab">
            Acceptées
            <% if @bookings.select { |booking| booking.status == 'Accepted' }.count > 0 %>
              <span class="notif"><%= @bookings.select { |booking| booking.status == 'Accepted' }.count %></span>
            <% end %>
        </button>
    </li>
    <li class="nav-item" role="presentation">
        <button class="nav-link" id="pending-tab" data-bs-toggle="tab" data-bs-target="#pending" type="button" role="tab">
            En attente
            <% if @bookings.select { |booking| booking.status == 'Pending' }.count > 0 %>
              <span class="notif"><%= @bookings.select { |booking| booking.status == 'Pending' }.count %></span>
            <% end %>
        </button>
    </li>
</ul>


    <div class="tab-content" id="reservationTabsContent">
        <div class="tab-pane fade show active" id="all" role="tabpanel">
            <div class="table-responsive">
                <table class="table table-hover align-middle">
                    <thead class="table-light">
                        <tr>
                            <th>Loueur</th>
                            <th>Status</th>
                            <th>Produit</th>
                            <th>Départ</th>
                            <th>Retour</th>
                            <th>Montant</th>
                        </tr>
                    </thead>
                    <tbody>
                      <% @bookings.each do |item| %>
                          <tr>
                            <td>
                              <%= link_to booking_path(item) do %>
                                <div class ="d-fex">

                                  <% if item.product.owner.photo.present? %>
                                    <%= cl_image_tag item.product.owner.photo.key, class: "avatar",  style: "max-width: 50px;" %>
                                  <% else %>
                                    <%= image_tag 'no_profile.png', class: "avatar", alt: "No picture available"%>
                                  <% end %>
                                  <%= item.product.owner.username %>
                                </div>
                              <% end %>
                            </td>
                            <% if item.status == "Pending" %>
                            <td>
                              <%= link_to booking_path(item) do %>
                                <span class="badge bg-secondary">
                                    <%= item.status.capitalize %>
                                </span>
                              <% end %>
                            </td>
                            <% else %>
                            <td>
                              <%= link_to booking_path(item) do %>
                                <span class="badge <%= item.status == 'Refused' ? 'bg-danger' : 'bg-success' %>">
                                  <%= item.status.capitalize %>
                                </span>
                              <% end %>
                            </td>
                            <% end %>
                            <% if item.product.photos.present? %>
                              <td><%= cl_image_tag item.product.photos[0].key , class: "rounded", height: 50, width: 50 %></td>
                            <% else %>
                              <td><%= image_tag 'no_picture.jpg', class: "rounded", alt: "No picture available", height: 50, width: 50 %></td>
                            <% end %>
                            <td><%= link_to item.start_date, booking_path(item) %></td>
                            <td><%= link_to item.end_date, booking_path(item) %></td>
                            <td><%= link_to "#{item.amount} €", booking_path(item) %></td>
                          </tr>
                      <% end %>

                    </tbody>
                </table>
            </div>
        </div>

        <div class="tab-pane fade" id="accepted" role="tabpanel">
            <div class="table-responsive">
                <table class="table table-hover align-middle">
                    <thead class="table-light">
                        <tr>
                            <th>Loueur</th>
                            <th>Status</th>
                            <th>Produit</th>
                            <th>Départ</th>
                            <th>Retour</th>
                            <th>Montant</th>
                        </tr>
                    </thead>
                    <tbody>
                      <% filtered_list = @bookings.select { |booking| booking.status == "Accepted"} %>
                      <% filtered_list.each do |item| %>
                        <tr>
                          <td>
                            <%= link_to booking_path(item) do %>
                              <div class ="d-fex">
                                <% if item.product.owner.photo.present? %>
                                    <%= cl_image_tag item.product.owner.photo.key, class: "avatar",  style: "max-width: 50px;" %>
                                  <% else %>
                                    <%= image_tag 'no_profile.png', class: "avatar", alt: "No picture available"%>
                                  <% end %>
                                <%= item.product.owner.username %>
                              </div>
                            <% end %>
                          </td>
                          <td><%= link_to booking_path(item) do %>
                            <span class="badge bg-success"><%= item.status.capitalize %></span>
                            <% end %>
                          </td>
                          <% if item.product.photos.present? %>
                            <td><%= cl_image_tag item.product.photos[0].key , class: "rounded", height: 50, width: 50 %></td>
                          <% else %>
                            <td><%= image_tag 'no_picture.jpg', class: "rounded", alt: "No picture available", height: 50, width: 50 %></td>
                          <% end %>
                          <td><%= link_to item.start_date, booking_path(item) %></td>
                          <td><%= link_to item.end_date, booking_path(item) %></td>
                          <td><%= link_to "#{item.amount} €", booking_path(item) %></td>
                        </tr>
                      <% end %>

                    </tbody>
                </table>
            </div>
        </div>

        <!-- Annulées -->
        <div class="tab-pane fade" id="cancelled" role="tabpanel">
            <div class="table-responsive">
                <table class="table table-hover align-middle">
                    <thead class="table-light">
                        <tr>
                            <th>Loueur</th>
                            <th>Status</th>
                            <th>Produit</th>
                            <th>Départ</th>
                            <th>Retour</th>
                            <th>Montant</th>
                        </tr>
                    </thead>
                    <tbody>
                      <% filtered_list = @bookings.select { |booking| booking.status == "Refused"} %>
                      <% filtered_list.each do |item| %>
                        <tr>
                          <td>
                            <%= link_to booking_path(item) do %>
                              <div class ="d-fex">
                                <% if item.product.owner.photo.present? %>
                                    <%= cl_image_tag item.product.owner.photo.key, class: "avatar",  style: "max-width: 50px;" %>
                                  <% else %>
                                    <%= image_tag 'no_profile.png', class: "avatar", alt: "No picture available"%>
                                  <% end %>
                                <%= item.product.owner.username %>
                              </div>
                            <% end %>
                          </td>
                          <td><%= link_to booking_path(item) do %>
                            <span class="badge bg-danger"><%= item.status.capitalize %></span>
                            <% end %>
                          </td>
                          <% if item.product.photos.present? %>
                            <td><%= cl_image_tag item.product.photos[0].key , class: "rounded", height: 50, width: 50 %></td>
                          <% else %>
                            <td><%= image_tag 'no_picture.jpg', class: "rounded", alt: "No picture available", height: 50, width: 50 %></td>
                          <% end %>
                          <td><%= link_to item.start_date, booking_path(item) %></td>
                          <td><%= link_to item.end_date, booking_path(item) %></td>
                          <td><%= link_to "#{item.amount} €", booking_path(item) %></td>
                        </tr>
                      <% end %>

                    </tbody>
                </table>
            </div>
        </div>

        <!-- En attente -->
        <div class="tab-pane fade" id="pending" role="tabpanel">
           <div class="table-responsive">
                <table class="table table-hover align-middle">
                    <thead class="table-light">
                        <tr>
                            <th>Loueur</th>
                            <th>Status</th>
                            <th>Produit</th>
                            <th>Départ</th>
                            <th>Retour</th>
                            <th>Montant</th>
                        </tr>
                    </thead>
                    <tbody>
                      <% filtered_list = @bookings.select { |booking| booking.status == "Pending"} %>
                      <% filtered_list.each do |item| %>
                        <tr>
                          <td>
                            <%= link_to booking_path(item) do %>
                              <div class ="d-fex">
                                <% if item.product.owner.photo.present? %>
                                    <%= cl_image_tag item.product.owner.photo.key, class: "avatar",  style: "max-width: 50px;" %>
                                  <% else %>
                                    <%= image_tag 'no_profile.png', class: "avatar", alt: "No picture available"%>
                                  <% end %>
                                <%= item.product.owner.username %>
                              </div>
                            <% end %>
                            </td>
                          <td><%= link_to booking_path(item) do %>
                            <span class="badge bg-secondary"><%= item.status.capitalize %></span>
                            <% end %>
                          </td>
                          <% if item.product.photos.present? %>
                            <td><%= cl_image_tag item.product.photos[0].key , class: "rounded", height: 50, width: 50 %></td>
                          <% else %>
                            <td><%= image_tag 'no_picture.jpg', class: "rounded", alt: "No picture available", height: 50, width: 50 %></td>
                          <% end %>
                          <td><%= link_to item.start_date, booking_path(item) %></td>
                          <td><%= link_to item.end_date, booking_path(item) %></td>
                          <td><%= link_to "#{item.amount} €", booking_path(item) %></td>
                        </tr>
                      <% end %>

                    </tbody>
                </table>
            </div>
        </div>
    </div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer">
  <div class="footer-container">
    <div class="footer-column">
      <h4>Services</h4>
      <ul>
        <li><a href="#">Louez du matériel</a></li>
        <li><a href="#">Rentabilisez votre matériel</a></li>
        <li><a href="#">Découvrir le catalogue</a></li>
      </ul>
    </div>
    <div class="footer-column">
      <h4>À propos</h4>
      <ul>
        <li><a href="#">Notre histoire</a></li>
        <li><a href="#">On recrute</a></li>
        <li><a href="#">Nouveautés <span class="new-badge">NEW</span></a></li>
        <li><a href="#">Roadmap <span class="new-badge">NEW</span></a></li>
      </ul>
    </div>
    <div class="footer-column">
      <h4>Assistance</h4>
      <ul>
        <li><a href="#">Centre d'aide</a></li>
        <li><a href="#">Aide locataire</a></li>
        <li><a href="#">Aide propriétaire</a></li>
        <li><a href="#">Nous contacter</a></li>
      </ul>
    </div>
  </div>

  <div class="footer-bottom">
    <div class="footer-legal">
      <p>© 2024 Kiloutools</p>
      <ul>
        <li><a href="#">CGU</a></li>
        <li><a href="#">Confidentialité</a></li>
        <li><a href="#">Assurance</a></li>
      </ul>
    </div>
    <div class="footer-social">
      <a href="#"><i class="fa-brands fa-facebook"></i></a>
      <a href="#"><i class="fa-brands fa-instagram"></i></a>
      <a href="#"><i class="fa-brands fa-linkedin"></i></a>
    </div>
  </div>
</footer>

app/views/shared/_grid_bookings.html.erb
<div class="product-cards">
  <% @bookings.each do |booking| %>
    <%= link_to booking_path(booking) do %>
      <div class="product-card">
        <div class="product-card-image">
          <img src="<%= booking.product.photos %>" alt="<%= booking.product.name %>">
          <div class="product-card-state"><%= booking.status %></div>
        </div>
        <div class="product-card-content">
          <h5 class="product-card-title"><%= booking.product.name %></h5>
          <p class="product-card-description"><%= booking.start_date %></p>
          <p class="product-card-description"><%= booking.end_date %></p>
          <p class="product-card-price"><%= booking.amount %> €</p>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/shared/_grid_offers.html.erb
<div class="product-cards">
  <% products.each do |product| %>
  <%= link_to product_path(product), class: "product-link" do %>
    <div class="product-card">
      <div class="card-header">
        <div class="availability">
          <span class="status-circle"></span>
          <span>Disponibilité confirmée</span>
        </div>
        <div class="product-card-image">
          <%= render 'shared/products_carroussel', product: product %>
        </div>
        <p class="price"><%= product.price %>€/jour</p>
        <% if product.owner.photo.present? %>
          <%= image_tag product.owner.photo, class: "profile-img", alt: "#{product.owner.username}", onerror: "this.onerror=null;this.src='#{asset_path('no_profile.png')}';" %>
        <% else %>
          <%= image_tag 'no_profile.png', class: "profile-img", alt: "No picture available" %>
        <% end %>
      </div>

      <div class="card-body">
         <p class="location">
          <span>📍</span> <%= product.owner.address %>
        </p>
        <h3><%= product.name %></h3>
        <p class="description">
          <%= product.description %>
        </p>

      </div>

      <div class="card-footer">
        <div class="footer-details">
          <div class="tags">
            <span class="tag"><%= product.category.name %></span>
          </div>
          <div class="rating">
            ⭐⭐⭐⭐⭐ <span>(2)</span>
          </div>
        </div>

      </div>
    </div>
    <% end %>
  <% end %>

</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "/" do %>
      <%= image_tag "logo_kiloutools.png", class: "logo" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Ma boutique", stores_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Mes réservations", bookings_path(current_user), class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <% if current_user.photo.attached? %>
              <%= cl_image_tag current_user.photo.key, class: "avatar", alt: "dropdown menu" %>
            <% else %>
              <img src="https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png" class="avatar" alt="dropdown menu" >
            <% end %>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Profile", profile_path(current_user), class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Connexion", new_user_session_path, class: "btn" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_products_carroussel.html.erb
<div id="carousel-<%= product.id %>" class="carousel slide w-100 mx-auto" data-bs-ride="carousel">

  <div class="carousel-indicators">
    <% product.photos.each_with_index do |photo, index| %>
      <button
        type="button"
        data-bs-target="#carousel<%= index %>s"
        data-bs-slide-to="<%= index %>"
        class="<%= 'active' if index == 0 %>"
        aria-current="<%= 'true' if index == 0 %>"
        aria-label="Slide <%= index + 1 %>">
      </button>
    <% end %>
  </div>

<!-- Images du carrousel -->
  <div class="carousel-inner">
    <% product.photos.each_with_index do |photo, index| %>
      <div class="carousel-item <%= 'active' if index == 0 %>">
        <%= cl_image_tag photo.key, class: "d-block w-100", height: 300, width: 400, crop: :fill, alt: "Photo #{index + 1}" %>
      </div>
    <% end %>
  </div>

  <!-- Contrôles de navigation -->
   <% if product.photos.any? %>
    <button class="carousel-control-prev" type="button" data-bs-target="#carousel-<%= product.id %>" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carousel-<%= product.id %>" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  <% end %>
</div>