config/routes.rb
Rails.application.routes.draw do
  get 'store/index'
  devise_for :users
  root to: "pages#home"

  get "up" => "rails/health#show", as: :rails_health_check

  resources :products do
    resources :bookings, only: [:create]

    collection do
      get :search
    end

    member do
      patch 'update_active'
      patch 'add_photos'
      delete 'destroy_photo'
    end

  end

  resources :bookings, only: [:show, :index, :destroy, :update]
  resources :profiles, only: [:show, :update]
  resources :stores, only: [:index]
  get 'stores/ads', to: 'products#summary', as: 'product_summary'
end

app/models/product.rb
class Product < ApplicationRecord
  include PgSearch::Model
  STATES = ["Neuf", "Comme neuf", "Très bon état", "Bon état", "Usagé"]

  belongs_to :brand
  belongs_to :category
  belongs_to :owner, class_name: 'User', foreign_key: 'user_id'

  has_many :bookings
  has_many :customers

  has_many_attached :photos

  validates :name, :description, :state, :model, :price, presence: true
  validates :state, inclusion: { in: STATES }
  validates :price, numericality: { greater_than_or_equal_to: 0 }

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_user_id?

  pg_search_scope :global_search,
  against: [ :name ],
  associated_against: {
    category: [ :name ],
    brand: [ :name ],
  },
  using: {
    tsearch: { prefix: true }
  }

  def can_be_destroyed?
    bookings.empty?
  end

  def address
    owner.address
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!, only: [:summary, :update_active]
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :load_products, only: [:index, :search]
  skip_before_action :verify_authenticity_token, only: [:update_active]

  def index
    @bookings_dates = {}.to_json
  end

  def show
    @booking = Booking.new()
    @start_date = Date.strptime(session[:start_date], "%d-%m-%Y") if session[:start_date]
    @end_date = Date.strptime(session[:end_date], "%d-%m-%Y") if session[:end_date]

    @count_products_per_owner = count_products_per_owner
    @place_name = find_place_name
    @markers = [{lat: @product.latitude, lng: @product.longitude}]

    @bookings = @product.bookings.where(status: ['Pending', 'Accepted'])
    @bookings_dates = @bookings.map do |booking|
      {
        from: booking.start_date,
        to: booking.end_date
      }
    end.to_json
  end

  def search
    render :index
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    @product.user_id = current_user.id

    begin
      if @product.save
        # ajout des photos issues du submit new
        @product.photos.attach(params[:product][:photos])

        # flash[:notice] = "Product was successfully created"
        redirect_to product_path(@product)
      else
        # flash[:alert] = "Failed to create product"
        render :new, status: :unprocessable_entity
      end
    rescue => e
      Rails.logger.error("Error creating product: #{e}")
      Rails.logger.debug @product.inspect
      # flash[:alert] = "Failed to create product"
      redirect_back(fallback_location: root_path)
      # render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    begin
      if @product.update(product_params)
        # ajout des photos issues du submit edit
        @product.photos.attach(params[:product][:photos])
        # flash[:notice] = "Product was successfully updated"
        redirect_to product_path(@product)
      else
        # flash[:alert] = "Failed to update product"
        render :edit
      end
    rescue => e
      Rails.logger.error("Error creating product: #{e}")
      Rails.logger.debug @product.inspect
      # flash[:alert] = "Failed to update product"
      redirect_back(fallback_location: root_path)
    end
  end

  def destroy_photo
    @product = Product.find(params[:id])
    @photo = ActiveStorage::Attachment.find(params[:photo_id])

    @photo.purge # Supprime la photo du stockage
    redirect_to edit_product_path(@product), notice: "Photo supprimée avec succès."
  end

  def add_photos
    @product = Product.find(params[:id])
    begin
      if @product.update(product_params)
        # ajout des photos issues du submit edit
        @product.photos.attach(params[:product][:photos])
        # flash[:notice] = "Product was successfully updated"
        redirect_to edit_product_path(@product), notice: "Photo(s) ajoutée(s) avec succès."
      else
        # flash[:alert] = "Failed to update product"
        render :edit
      end
    rescue => e
      Rails.logger.error("Error creating product: #{e}")
      Rails.logger.debug @product.inspect
      # flash[:alert] = "Failed to update product"
      redirect_back(fallback_location: root_path)
    end
  end

  def destroy
    begin
      if @product.destroy
        # flash[:notice] = "Product was successfully destroyed"
        redirect_to products_path
      else
        # flash[:alert] = "Failed to delete product"
        redirect_to product_path(@product)
      end
    rescue => e
      # log_error(e)
      Rails.logger.error("Error creating product: #{e}")
      Rails.logger.debug @product.inspect
      # flash[:alert] = "Failed to delete product"
      redirect_back(fallback_location: root_path)
    end
  end

  def summary
    @user = current_user
    @products = Product.where(user_id: @user)
  end

  def update_active
    @product = Product.find(params[:id])
    active_status = params[:active]
    if @product.update(active: active_status)
      render json: { success: true, active: @product.active }
    else
      render json: { success: false, error: 'Erreur de mise à jour' }, status: 400
    end
  end

  private

  def product_params
    # Les photos ne sont plus dans le permit car ça ne fonctionne pas
    # pour la gestion des ajouts ou suppression unitaires
    # La construction du tableau photos se fait dans update et save
    params.require(:product).permit(:name, :description, :state, :model, :price, :category_id, :brand_id)
  end

  def search_params
    params.fetch(:search, {}).permit(:name, :address, :start_date, :end_date)
  end

  def set_product
    begin
      @product = Product.find(params[:id])
    rescue => e
      # log_error(e)
      Rails.logger.error("Error creating product: #{e}")
      Rails.logger.debug @product.inspect
      # flash[:alert] = "Product not found"
      redirect_to products_path
    end
  end

  def load_products
    @search_params = search_params || {}
    @products = filter_products(params[:search])
    @markers = set_markers(@products)

    session[:start_date] = params[:search][:start_date] if params[:search].present? && params[:search][:start_date].present?
    session[:end_date] = params[:search][:end_date] if params[:search].present? && params[:search][:end_date].present?
  end

  def filter_products(search_params)
    products = Product.all

    if search_params.present?
      if search_params[:address].present?
        products = products.near(search_params[:address], 10)
      end
      if search_params[:name].present?
        products = Product.global_search(search_params[:name])
      end
      if search_params[:start_date].present? && search_params[:end_date].present?
        start_date = Date.parse(search_params[:start_date])
        end_date = Date.parse(search_params[:end_date])

        products = products.select do |product|
          product.bookings.none? do |booking|
            (booking.start_date <= end_date) && (booking.end_date >= start_date)
          end
        end
      end
    end

    products = products.select { |product| product.active }
  end

  def set_markers(products)
    products.map do |product|
      {
        lat: product.latitude,
        lng: product.longitude,
      }
    end
  end

  def find_place_name
    results = Geocoder.search(@product.owner.address)
    if results.present? && results.first.data["address"]
      results.first.city || "Inconnu"
    else
      "Aucune information disponible"
    end
  end

  def count_products_per_owner
    return Product.where(user_id: @product [:user_id]).count
  end

end

app/views/products/_form.html.erb
<!-- Affectation du chemin de retour en fonction de l'origine  -->
<% back_path = if controller_name == "products" && action_name == "new" %>
  <% title_page = "Création de votre produit" %>
  <% label_submit = "Créer le produit" %>
  <% back_path = products_path %>
<% elsif controller_name == "products" && action_name == "edit" %>
  <% title_page = "Modification de votre produit" %>
  <% label_submit = "Enregistrer les modifications" %>
  <% back_path = product_path(@product) %>
<% else %>
  <% title_page = "Gestion de votre produit" %>
  <% label_submit = "Enregistrer" %> <!-- Valeur par défaut -->
  <% back_path = root_path %> <!-- Valeur par défaut -->
<% end %>

<!-- Formulaire du produit utilisé pour new et edit -->
<div class="pdt-main-container">
  <h1><%= title_page %></h1>
  <div class="pdt-container">
  <div class="pdt-container-left">
    <%= simple_form_for @product do |f| %>
      <div class="">
        <%= f.input :name, label: "Nom du produit" %>
        <%= f.association :category, label: "Catégorie" %>
        <%= f.association :brand, label: "Marque" %>
        <%= f.input :model, label: "Modèle" %>
        <%= f.input :description, label: "Description du produit" %>
        <%= f.input :state, as: :select, label: "Etat", collection: Product::STATES, include_blank: "Sélectionner un état" %>
        <%= f.input :price, label: "Prix de location à la journée" %>
        <!-- <%= f.input :photos, as: :file, label: "Sélectionner vos photos", input_html: { multiple: true } %> -->
      </div>

      <div class="btn-line">
        <%= link_to "Annuler", back_path, class: "btn btn-secondary" %>
        <%= f.button :submit, label_submit, class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>

  <div class="pdt-container-right">

    <!-- Zone de gestion des photos du produits -->
    <% if @product.persisted? %>
    <h1 class="product-title">Photos du produit</h1>
    <p class="fs-6">Ajouter des photos pour mettre en valeur votre produit</p>
    <%= link_to "Ajouter des photos", "#addPhotosModal", class: "btn btn-primary my-3", data: { bs_toggle: "modal" } %>
    <div class="ph-container">
      <% @product.photos.each_with_index do |photo, index| %>
        <div class="thumb">
          <!-- Afficher l'image depuis Cloudinary -->
          <%= cl_image_tag photo.key, class: "ph-card", alt: "Photo #{index + 1}" %>

          <!-- Icône poubelle pour suppression -->
          <div class="ph-trash">
            <%= link_to destroy_photo_product_path(photo_id: photo), data: {turbo_method: "delete", turbo_confirm: "are you sure ?"}, class: "btn btn-danger btn-sm position-absolute bottom-0 end-0 m-2" do %>
              <i class="bi bi-trash"></i>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
    <!-- Modale Bootstrap pour l'ajout des images -->
    <div class="modal fade" id="addPhotosModal" tabindex="-1" aria-labelledby="addPhotosModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="addPhotosModalLabel">Ajouter des photos</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
            <%= simple_form_for @product, url: add_photos_product_path(@product), method: :patch, html: { multipart: true } do |f| %>
              <%= f.input :photos, as: :file, label: "Sélectionnez vos photos", input_html: { multiple: true } %>
              <%= f.submit "Ajouter", class: "btn btn-primary mt-3" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <% else %>
      <div class="">
        <p class="color-danger">Enregistrez le produit avant d'ajouter des photos.</p>
      </div>
    <% end %>

  </div>
  </div>
</div>

app/views/products/_modal_delete.html.erb
<div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="deleteModalLabel">Confirm Deletion</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        Are you sure you want to delete this item?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
        <%= button_to "Delete", product_path(@product), method: :delete, class: "btn btn-danger", form: { id: "deleteForm" } %>
      </div>
    </div>
  </div>
</div>

app/views/products/_product_search_form.html.erb
<div class="search-container" data-controller="toggle-form">
  <div class="search-summary" data-toggle-form-target="summary" data-action="click->toggle-form#expand">
    <div class="search-details">
      <p>
        <span class="label">Produit</span>
        <span data-toggle-form-target = "product">
          <%= params.dig(:search, :name).blank? ? "Tous" : params.dig(:search, :name) %>
        </span>
      </p>

      <p>
        <span class="label">Ville</span>
        <span data-toggle-form-target = "city">
          <%= params.dig(:search, :address).blank? ? "Partout" : params.dig(:search, :address) %>
        </span>
      </p>

      <p>
        <span class="label">Départ</span>
        <span>
          <span data-toggle-form-target = "startDate">
            <%= params.dig(:search, :start_date).blank? ? "" : params.dig(:search, :start_date) %>
          </span>
        </span>
      </p>
      <p>
        <span class="label">Retour</span>
        <span data-toggle-form-target = "endDate">
          <%= params.dig(:search, :end_date).blank? ? "" : params.dig(:search, :end_date) %>
        </span>
      </p>
    </div>

    <div class="rounded-btn">
      <%= image_tag "filter-32.svg"%>
    </div>
  </div>

  <div class="search-form d-none" data-toggle-form-target="form" data-controller="datepicker">
    <%= simple_form_for :search, url: search_products_path, method: :get, html: { class: 'row align-items-center justify-content-center' } do |f| %>
      <div class="col-3 px-1">
        <%= f.input :name,
                    label: false,
                    placeholder: "Perceuse, Visseuse, Scie...",
                    wrapper_html: { style: 'margin-bottom: 0 !important'},
                    input_html: {
                      class: 'form-control',
                      value: params.dig(:search, :name),
                      data: { toggle_form_target: 'productInput' }
                    },
                    required: false %>
      </div>

      <div class="col-4 px-1" data-controller='mapbox-autocomplete'
    data-mapbox-autocomplete-api-key-value=<%= ENV["MAPBOX_API_KEY"] %>>
        <%= f.input :address,
                    label: false,
                    placeholder: "Lille, Paris, Tourcoing...",
                    wrapper_html: { style: 'margin-bottom: 0 !important'},
                    input_html: {
                      class: 'form-control',
                      value: params.dig(:search, :address),
                      autocomplete: 'off',
                      data: {
                        action: 'input->mapbox-autocomplete#search',
                        mapbox_autocomplete_target: 'input',
                        toggle_form_target: 'cityInput'
                      }
                    },
                    required: false %>
        <div id='mapbox-autocomplete' data-mapbox-autocomplete-target="results" ></div>
      </div>

      <%= f.hidden_field :bookings_dates, value: [], data: { datepicker_target: "bookingsDates" } %>

      <div class="col-2 px-1">
        <%= f.text_field :start_date,
                          class: "form-control",
                          label: false,
                          placeholder: "Début",
                          value: params.dig(:search, :start_date)&.to_date&.strftime("%Y-%m-%d"),
                          data: {
                            datepicker_target: "startDate",
                            toggle_form_target: "startDateInput"
                          } %>
      </div>

      <div class="col-2 px-1">
        <%= f.text_field :end_date,
                          class: "form-control",
                          label: false,
                          placeholder: "Fin",
                          value: params.dig(:search, :end_date)&.to_date&.strftime("%Y-%m-%d"),
                          data: {
                            datepicker_target: "endDate",
                            toggle_form_target: "endDateInput"
                          } %>
      </div>
      <%= button_tag type: "submit", class: "rounded-btn" do %>
        <div>
          <i class="fa-solid fa-magnifying-glass"></i>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/products/edit.html.erb
<%= render 'form', product: @product %>

app/views/products/index.html.erb
<div class="products">
  <div class="left-container">
    <%= render "product_search_form" %>

    <div class="products-grid p-3">
      <% if @products.any? %>
          <p><strong><%= @products.size %></strong> produit(s) trouvé(s)</p>
          <%= render 'shared/grid_offers', products: @products%>
      <% else %>
        <p>Aucun produit trouvé pour cette recherche.</p>
      <% end %>
    </div>
  </div>

  <div class="right-container">
    <div class="map" id="map" data-controller="map"
      data-map-api-key-value='<%= ENV["MAPBOX_API_KEY"] %>'
      data-map-markers-value='<%= raw @markers.to_json %>'>
    </div>
  </div>
</div>

app/views/products/new.html.erb
<%= render 'form', product: @product %>

app/views/products/show.html.erb
<%= render "modal_delete" %>

<div class="product-container">

  <div class="left-container">
    <div class="product-details">
      <div>
        <span class="badge text-bg-secondary"><%= @product.state %></span>
        <h1 class="product-title"><%= @product.name %></h1>
        <p class="info-value"><%= @product.category.name %></p>
      </div>
      <div class="price">
        <h4 class="fw-bold m-0"><%= @product.price %> €</h4>
        <p class="info-value">par jour</p>
      </div>
    </div>

    <div class="product-image">
      <% if @product.photos.present? %>
        <%= render 'shared/products_carroussel', product: @product %>
      <% else %>
        <%= image_tag 'no_picture.jpg', class: "mx-auto", alt: "No picture available" %>
      <% end %>
    </div>

    <div class="owner-info">
      <%= link_to profile_path(@product.owner) do %>
      <div class="owner-photo">
        <% if @product.owner.photo.present? %>
          <%= image_tag @product.owner.photo, class: "img-owner", alt: "#{@product.owner.username}", onerror: "this.onerror=null;this.src='#{asset_path('no_profile.png')}';" %>
        <% else %>
          <%= image_tag 'no_profile.png', class: "img-owner", alt: "No picture available" %>
        <% end %>
      </div>
      <% end %>

      <div class="owner-details">
        <div class="owner-location">
          <i class="bi bi-geo-alt color-black"></i>
          <p><%= @place_name %></p>
        </div>
        <div class="owner-name">
          <i class="fa-regular fa-circle-user"></i>
          <p><strong><%= @product.owner.username %></strong></p>
        </div>
      </div>

      <div class="owner-stats">
        <div class="owner-joined">
          <i class="bi bi-calendar3 color-black"></i>
          <p class="joined-date"><%= @product.owner.created_at.strftime("%d-%m-%Y") %></p>
        </div>
        <div class="owner-products">
          <i class="bi bi-tools"></i>
          <p class="products-count"><%= @count_products_per_owner %></p>
        </div>
      </div>
    </div>

    <div class="product-info-group">
      <div class="product-info">
        <p class="info-label"><strong>Catégorie</strong></p>
        <p class="info-value"><%= @product.category.name %></p>
      </div>
      <div class="product-info">
        <p class="info-label"><strong>Marque</strong></p>
        <p class="info-value"><%= @product.brand.name %></p>
      </div>
      <div class="product-info">
        <p class="info-label"><strong>Modèle</strong></p>
        <p class="info-value"><%= @product.model %></p>
      </div>
    </div>

    <div class="product-description">
     <div class="product-info">
        <p class="info-label"><strong>Description</strong></p>
        <p class="info-value"><%= @product.description %></p>
      </div>
    </div>

    <div id="map" data-controller="map"
      data-map-api-key-value='<%= ENV["MAPBOX_API_KEY"] %>'
      data-map-markers-value='<%= raw @markers.to_json %>'>
    </div>

  </div>

  <div class="right-container">
    <%= render 'shared/add_booking_form', { booking: @booking, price: @product.price, bookings_dates: @bookings_dates, start_date: @start_date, end_date: @end_date }%>
  </div>

</div>

app/views/products/summary.html.erb
<div class="container my-5 dashboard-renter py-5">
  <div class="dashboard-header d-flex justify-content-between align-items-center mb-5">
    <div>
      <h1 class="dashboard-title fw-bold">Liste de vos annonces <span>👋</span></h1>
      <p class="dashboard-subtitle text-secondary fs-5">Gérez l'ensemble de vos annonces</p>
    </div>
  </div>

  <div class="my-annonces-list">
    <% @products.each do |product| %>
      <div class="my-annonces-item d-flex p-3 mb-3 align-items-center">
        <!-- Image produit -->
        <div class="my-annonces-image">
          <% if product.photos.present? %>
            <%= cl_image_tag product.photos[0].key, class: "img-thumbnail rounded my-annonces-img", height: 100, width: 100 %>
          <% else %>
            <%= image_tag 'no_picture.jpg', class: "img-thumbnail rounded my-annonces-img", alt: "No picture available", height: 100, width: 100 %>
          <% end %>
        </div>

        <!-- Informations produit -->
        <div class="my-annonces-details ms-3 flex-grow-1">
          <h5 class="my-annonces-title mb-1"><%= product.name %></h5>
          <p class="my-annonces-description mb-1"><%= product.description %></p>
        </div>


        <div class="form-check-summary form-switch me-3" data-controller="toggle-product">
          <input class="form-check-input" type="checkbox" role="switch" id="product_<%= product.id %>"
                 <%= "checked" if product.active %>
                 data-action="change->toggle-product#toggle"
                 data-toggle-product-target="checkbox"
                 data-product-id="<%= product.id %>">
          <span class="badge-summary ms-2 <%= product.active ? 'bg-success' : 'bg-danger' %>" data-toggle-product-target="badge">
            <%= product.active ? 'En ligne' : 'Hors ligne' %>
          </span>
        </div>


        <div class="my-annonces-actions d-flex flex-column align-items-center">
          <%=  link_to edit_product_path(product) do%>
            <i class="fa-solid fa-ellipsis-vertical fs-1 text-secondary mx-3"></i>
          <% end %>

        </div>
      </div>
    <% end %>
  </div>
</div>